name: Buildx branch
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
    paths:
      - .github/workflows/buildx-branch.yml
      - .dockerignore
      - Dockerfile
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Run Buildx
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64 \
            -t qmcgaw/protoc:${GITHUB_REF##*/} \
            --push \
            .
      - run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/protoc/tQFy7AxtSUNANPe6aoVChYdsI_I= || exit 0
